name = "PowerSystemsControl"
uuid = "d51a28fe-693e-4736-bc11-7dd269f70161"
authors = ["viniciusjusten <viniciusjusten@psr-inc.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
